<?php

namespace VeryBuy\Payment\SinoPac;

interface CurrencyContract
{
      const AFN = 'AFN'; // Afghanistan Afghani
      const ARS = 'ARS'; // Argentina Peso
      const AWG = 'AWG'; // Aruba Guilder
      const AUD = 'AUD'; // Australia Dollar
      const AZN = 'AZN'; // Azerbaijan New Manat
      const BSD = 'BSD'; // Bahamas Dollar
      const BBD = 'BBD'; // Barbados Dollar
      const BDT = 'BDT'; // Bangladeshi taka
      const BYR = 'BYR'; // Belarus Ruble
      const BZD = 'BZD'; // Belize Dollar
      const BMD = 'BMD'; // Bermuda Dollar
      const BOB = 'BOB'; // Bolivia Boliviano
      const BAM = 'BAM'; // Bosnia and Herzegovina Convertible Marka
      const BWP = 'BWP'; // Botswana Pula
      const BGN = 'BGN'; // Bulgaria Lev
      const BRL = 'BRL'; // Brazil Real
      const BND = 'BND'; // Brunei Darussalam Dollar
      const KHR = 'KHR'; // Cambodia Riel
      const CAD = 'CAD'; // Canada Dollar
      const KYD = 'KYD'; // Cayman Islands Dollar
      const CLP = 'CLP'; // Chile Peso
      const CNY = 'CNY'; // China Yuan Renminbi
      const COP = 'COP'; // Colombia Peso
      const CRC = 'CRC'; // Costa Rica Colon
      const HRK = 'HRK'; // Croatia Kuna
      const CUP = 'CUP'; // Cuba Peso
      const CZK = 'CZK'; // Czech Republic Koruna
      const DKK = 'DKK'; // Denmark Krone
      const DOP = 'DOP'; // Dominican Republic Peso
      const XCD = 'XCD'; // East Caribbean Dollar
      const EGP = 'EGP'; // Egypt Pound
      const SVC = 'SVC'; // El Salvador Colon
      const EEK = 'EEK'; // Estonia Kroon
      const EUR = 'EUR'; // Euro Member Countries
      const FKP = 'FKP'; // Falkland Islands (Malvinas) Pound
      const FJD = 'FJD'; // Fiji Dollar
      const GHC = 'GHC'; // Ghana Cedis
      const GIP = 'GIP'; // Gibraltar Pound
      const GTQ = 'GTQ'; // Guatemala Quetzal
      const GGP = 'GGP'; // Guernsey Pound
      const GYD = 'GYD'; // Guyana Dollar
      const HNL = 'HNL'; // Honduras Lempira
      const HKD = 'HKD'; // Hong Kong Dollar
      const HUF = 'HUF'; // Hungary Forint
      const ISK = 'ISK'; // Iceland Krona
      const INR = 'INR'; // India Rupee
      const IDR = 'IDR'; // Indonesia Rupiah
      const IRR = 'IRR'; // Iran Rial
      const IMP = 'IMP'; // Isle of Man Pound
      const ILS = 'ILS'; // Israel Shekel
      const JMD = 'JMD'; // Jamaica Dollar
      const JPY = 'JPY'; // Japan Yen
      const JEP = 'JEP'; // Jersey Pound
      const KZT = 'KZT'; // Kazakhstan Tenge
      const KPW = 'KPW'; // Korea (North) Won
      const KRW = 'KRW'; // Korea (South) Won
      const KGS = 'KGS'; // Kyrgyzstan Som
      const LAK = 'LAK'; // Laos Kip
      const LVL = 'LVL'; // Latvia Lat
      const LBP = 'LBP'; // Lebanon Pound
      const LRD = 'LRD'; // Liberia Dollar
      const LTL = 'LTL'; // Lithuania Litas
      const MKD = 'MKD'; // Macedonia Denar
      const MYR = 'MYR'; // Malaysia Ringgit
      const MUR = 'MUR'; // Mauritius Rupee
      const MXN = 'MXN'; // Mexico Peso
      const MNT = 'MNT'; // Mongolia Tughrik
      const MZN = 'MZN'; // Mozambique Metical
      const NAD = 'NAD'; // Namibia Dollar
      const NPR = 'NPR'; // Nepal Rupee
      const ANG = 'ANG'; // Netherlands Antilles Guilder
      const NZD = 'NZD'; // New Zealand Dollar
      const NIO = 'NIO'; // Nicaragua Cordoba
      const NGN = 'NGN'; // Nigeria Naira
      const NOK = 'NOK'; // Norway Krone
      const OMR = 'OMR'; // Oman Rial
      const PKR = 'PKR'; // Pakistan Rupee
      const PAB = 'PAB'; // Panama Balboa
      const PYG = 'PYG'; // Paraguay Guarani
      const PEN = 'PEN'; // Peru Nuevo Sol
      const PHP = 'PHP'; // Philippines Peso
      const PLN = 'PLN'; // Poland Zloty
      const QAR = 'QAR'; // Qatar Riyal
      const RON = 'RON'; // Romania New Leu
      const RUB = 'RUB'; // Russia Ruble
      const SHP = 'SHP'; // Saint Helena Pound
      const SAR = 'SAR'; // Saudi Arabia Riyal
      const RSD = 'RSD'; // Serbia Dinar
      const SCR = 'SCR'; // Seychelles Rupee
      const SGD = 'SGD'; // Singapore Dollar
      const SBD = 'SBD'; // Solomon Islands Dollar
      const SOS = 'SOS'; // Somalia Shilling
      const ZAR = 'ZAR'; // South Africa Rand
      const LKR = 'LKR'; // Sri Lanka Rupee
      const SEK = 'SEK'; // Sweden Krona
      const CHF = 'CHF'; // Switzerland Franc
      const SRD = 'SRD'; // Suriname Dollar
      const SYP = 'SYP'; // Syria Pound
      // const TWD = 'TWD'; // Taiwan New Dollar
      const TWD = 'NTD'; // Taiwan New Dollar
      const THB = 'THB'; // Thailand Baht
      const TTD = 'TTD'; // Trinidad and Tobago Dollar
      const TRY = 'TRY'; // Turkey Lira
      const TRL = 'TRL'; // Turkey Lira
      const TVD = 'TVD'; // Tuvalu Dollar
      const UAH = 'UAH'; // Ukraine Hryvna
      const GBP = 'GBP'; // United Kingdom Pound
      const USD = 'USD'; // United States Dollar
      const UYU = 'UYU'; // Uruguay Peso
      const UZS = 'UZS'; // Uzbekistan Som
      const VEF = 'VEF'; // Venezuela Bolivar
      const VND = 'VND'; // Viet Nam Dong
      const YER = 'YER'; // Yemen Rial
      const ZWD = 'ZWD'; // Zimbabwe Dollar
}